import { Injectable } from '@angular/core';
import { HttpClient, HttpHeaders, HttpErrorResponse } from '@angular/common/http';
import { catchError, map, Observable, throwError } from 'rxjs';
import { Task } from './task.model';
import { environment } from '../../enviroments/enviroment';

@Injectable({
    providedIn: 'root'
})
export class TaskService {
    private apiUrl = environment.apiUrl;
    private headers = new HttpHeaders().set('Content-Type', 'application/json');

    constructor(private http: HttpClient) { }

    getTasks(): Observable<Task[]> {
        return this.http.get<Task[]>(`${this.apiUrl}/tasks`, { headers: this.headers }).pipe(
            map(res => res),
            catchError(this.handleError)
        );
    }

    getTask(id: string): Observable<Task> {
        return this.http.get<Task>(`${this.apiUrl}/tasks/${id}`, { headers: this.headers }).pipe(
            map(res => res),
            catchError(this.handleError)
        );;
    }

    createTask(task: Task): Observable<Task> {
        return this.http.post<Task>(`${this.apiUrl}/tasks`, task, { headers: this.headers }).pipe(
            map(res => res),
            catchError(this.handleError)
        );
    }

    updateTask(task: Task): Observable<Task> {
        return this.http.put<Task>(`${this.apiUrl}/tasks/${task.id}`, task, { headers: this.headers }).pipe(
            map(res => res),
            catchError(this.handleError)
        );
    }

    deleteTask(id: string): Observable<Task> {
        return this.http.delete<Task>(`${this.apiUrl}/tasks/${id}`, { headers: this.headers }).pipe(
            map(res => res),
            catchError(this.handleError)
        );;
    }

    private handleError(error: HttpErrorResponse) {
        let errorMessage;
        if (error.error instanceof ErrorEvent) {
            // client-side error
            errorMessage = error.error.message;
        } else {
            // server-side error
            errorMessage = `Error Code: ${error.status}\nMessage: ${error.message}`;
        }

        console.error(errorMessage);
        const errorObject = { name: 'HttpError', message: errorMessage };
        return throwError(() => errorObject);
    }
}